name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
      - run: yarn install --frozen-lockfile
      - run: yarn ci

  test-macos-integration:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-15, macos-26, xcode-27]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
      - run: npx -y --min-release-age=0 @guidepup/setup@0.28.0 setup --ci
      - run: yarn install --frozen-lockfile
      - run: yarn test:int:macos

  test-windows-integration:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022, windows-2025]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
      - run: yarn install --frozen-lockfile
      - run: yarn test:int:windows
